#!/usr/bin/env bash
# deploy.sh — run on the SERVER as appuser to install and start the application.
#
# First deploy:
#   bash deploy.sh
#
# Re-deploy after pushing new code:
#   bash deploy.sh --update
#
# Prerequisites (handled automatically):
#   - uv, nvm/Node 20, nginx, certbot, bubblewrap, ffmpeg
#
# The script is idempotent: safe to re-run.

set -euo pipefail

# ── Configuration — fill these in before copying to the server ────────────────

REPO_URL="https://github.com/r-dug/teacher_agent.git"
DOMAIN="tutorail.app"           # e.g. learnwith.dev  — REQUIRED

# ── Internal vars ─────────────────────────────────────────────────────────────

APP_DIR="$HOME/app"
STORAGE_DIR="/var/lib/pdf-to-audio/storage"
UPDATE_ONLY="${1:-}"

# ── Validation ────────────────────────────────────────────────────────────────

if [ -z "$DOMAIN" ]; then
    echo "ERROR: Set DOMAIN at the top of deploy.sh before running."
    exit 1
fi

if [ "$REPO_URL" = "https://github.com/YOUR_USERNAME/YOUR_REPO.git" ]; then
    echo "ERROR: Set REPO_URL at the top of deploy.sh before running."
    exit 1
fi

APP_URL="https://$DOMAIN"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  pdf-to-audio deploy"
echo "  Domain : $DOMAIN"
echo "  App dir: $APP_DIR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── 1. System packages ────────────────────────────────────────────────────────

echo "[1/9] Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y -qq \
    nginx certbot python3-certbot-nginx \
    git curl build-essential \
    libmagic1 pkg-config bubblewrap ffmpeg \
    sqlite3 libportaudio2

# ── 2. uv ─────────────────────────────────────────────────────────────────────

echo "[2/9] Installing uv..."
if ! command -v "$HOME/.local/bin/uv" &>/dev/null; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi
export PATH="$HOME/.local/bin:$PATH"

# ── 3. Node 20 (build step only — not needed at runtime) ─────────────────────

echo "[3/9] Installing Node 20 via nvm..."
export NVM_DIR="$HOME/.nvm"
if [ ! -d "$NVM_DIR" ]; then
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
fi
# shellcheck source=/dev/null
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
nvm install 20 --silent
nvm use 20

# ── 4. Clone / update repo ────────────────────────────────────────────────────

echo "[4/9] Fetching application code..."
if [ -d "$APP_DIR/.git" ]; then
    echo "  Repo exists — pulling latest..."
    git -C "$APP_DIR" pull --ff-only
else
    git clone "$REPO_URL" "$APP_DIR"
fi
cd "$APP_DIR"

# ── 5. Python deps + React build ─────────────────────────────────────────────

echo "[5/9] Installing Python dependencies..."
"$HOME/.local/bin/uv" sync
# Kokoro TTS and Whisper STT require pip to be present in the venv.
# Must run after uv sync so it uses the project's venv.
"$HOME/.local/bin/uv" pip install pip

echo "  Building React client..."
source "$NVM_DIR/nvm.sh" && nvm use 20
cd client && npm ci --silent && npm run copy-vad-assets && npm run build
cd "$APP_DIR"

# ── 6. Storage directory ──────────────────────────────────────────────────────

echo "[6/9] Setting up persistent storage at $STORAGE_DIR..."
sudo mkdir -p "$STORAGE_DIR"
sudo chown "$USER:$USER" "$STORAGE_DIR"

# ── 7. .env file ─────────────────────────────────────────────────────────────

echo "[7/9] Configuring environment..."
if [ ! -f "$APP_DIR/.env" ]; then
    echo ""
    echo "  Enter your configuration values."
    echo "  (Values are written to $APP_DIR/.env with mode 600)"
    echo ""

    read -rp "  ANTHROPIC_API_KEY          : " _ANTHROPIC_KEY
    read -rp "  RESEND_API_KEY             : " _RESEND_KEY
    echo "  (Leave blank → verification links log to journald instead of email)"
    read -rp "  FROM_EMAIL [noreply@${DOMAIN}]: " _FROM_EMAIL
    _FROM_EMAIL="${_FROM_EMAIL:-noreply@${DOMAIN}}"
    read -rp "  Notification email for TLS cert (Let's Encrypt): " _CERTBOT_EMAIL

    _BACKEND_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")

    cat > "$APP_DIR/.env" << EOF
# Generated by deploy.sh — do not commit this file
ENV=production

# API keys
ANTHROPIC_API_KEY=${_ANTHROPIC_KEY}
RESEND_API_KEY=${_RESEND_KEY}

# Auth / email
FROM_EMAIL=${_FROM_EMAIL}
APP_URL=${APP_URL}
ALLOWED_ORIGINS=${APP_URL}

# Storage
STORAGE_DIR=${STORAGE_DIR}
DB_PATH=${STORAGE_DIR}/db.sqlite3

# Models
STT_MODEL_SIZE=medium
LLM_MODEL=claude-sonnet-4-6
DEFAULT_VOICE=af_heart

# BFF→backend shared secret (generated at first deploy — do not change without restarting both services)
BACKEND_SHARED_SECRET=${_BACKEND_SECRET}
EOF

    # Store certbot email separately (not needed by the app itself)
    echo "$_CERTBOT_EMAIL" > "$APP_DIR/.certbot_email"
    chmod 600 "$APP_DIR/.env" "$APP_DIR/.certbot_email"
    echo "  .env written."
else
    echo "  .env already exists — skipping."
fi

CERTBOT_EMAIL="$(cat "$APP_DIR/.certbot_email" 2>/dev/null || echo "admin@${DOMAIN}")"

# ── 8. Systemd services ───────────────────────────────────────────────────────

echo "[8/9] Installing systemd services..."

sudo tee /etc/systemd/system/pdf-backend.service > /dev/null << EOF
[Unit]
Description=pdf-to-audio Backend
After=network.target

[Service]
Type=simple
User=${USER}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${APP_DIR}/.env
ExecStart=${APP_DIR}/.venv/bin/python -m backend.main
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

sudo tee /etc/systemd/system/pdf-frontend.service > /dev/null << EOF
[Unit]
Description=pdf-to-audio Frontend BFF
After=pdf-backend.service
Requires=pdf-backend.service

[Service]
Type=simple
User=${USER}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${APP_DIR}/.env
ExecStart=${APP_DIR}/.venv/bin/python -m frontend.main
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable pdf-backend pdf-frontend
sudo systemctl restart pdf-backend pdf-frontend
echo "  Services started."

# ── 9. nginx + TLS ───────────────────────────────────────────────────────────

echo "[9/9] Configuring nginx and TLS..."

# Wait for the BFF to be ready (backend loads Kokoro TTS which takes ~30s).
# Retry for up to 90 seconds before giving up.
echo "  Waiting for services to be ready (up to 90s)..."
TLS_SKIP=true
for i in $(seq 1 18); do
    if curl -sf --max-time 5 "http://127.0.0.1/health" -o /dev/null; then
        TLS_SKIP=false
        break
    fi
    echo "  ... attempt $i/18, retrying in 5s"
    sleep 5
done

if [ "$TLS_SKIP" = "true" ]; then
    echo ""
    echo "  WARNING: services did not become ready within 90s."
    echo "  Check logs: journalctl -u pdf-backend -n 30"
    echo "  Skipping TLS setup — re-run this script once services are up."
    echo ""
fi

# Write nginx config (HTTP first; certbot will add HTTPS block)
sudo tee /etc/nginx/sites-available/pdf-to-audio > /dev/null << EOF
server {
    listen 80;
    server_name ${DOMAIN};
    client_max_body_size 50m;

    location / {
        proxy_pass         http://127.0.0.1:8000;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
    }

    # WebSocket upgrade
    location /ws/ {
        proxy_pass             http://127.0.0.1:8000;
        proxy_http_version     1.1;
        proxy_set_header       Upgrade    \$http_upgrade;
        proxy_set_header       Connection "upgrade";
        proxy_set_header       Host       \$host;
        proxy_set_header       X-Real-IP  \$remote_addr;
        proxy_read_timeout     3600s;
        proxy_send_timeout     3600s;
    }
}
EOF

sudo ln -sf /etc/nginx/sites-available/pdf-to-audio /etc/nginx/sites-enabled/
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t && sudo systemctl reload nginx

if [ "$TLS_SKIP" = "false" ]; then
    sudo certbot --nginx \
        -d "$DOMAIN" \
        --non-interactive \
        --agree-tos \
        -m "$CERTBOT_EMAIL"
    echo "  TLS certificate issued."

    # Auto-renew hook: reload nginx after cert renewal
    sudo tee /etc/letsencrypt/renewal-hooks/deploy/reload-nginx.sh > /dev/null << 'HOOK'
#!/bin/sh
systemctl reload nginx
HOOK
    sudo chmod +x /etc/letsencrypt/renewal-hooks/deploy/reload-nginx.sh
fi

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Deploy complete!"
echo ""
if [ "$TLS_SKIP" = "false" ]; then
    echo "  App URL   : https://$DOMAIN"
else
    echo "  App URL   : http://$DOMAIN  (TLS pending DNS propagation)"
    echo "  Run again after DNS propagates to complete HTTPS setup."
fi
echo ""
echo "  Logs:"
echo "    journalctl -u pdf-backend  -f"
echo "    journalctl -u pdf-frontend -f"
echo ""
echo "  Service status:"
echo "    systemctl status pdf-backend pdf-frontend"
echo ""
echo "  To redeploy after a code push:"
echo "    bash deploy.sh --update"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
